feat: signout api integration
kalvilabs/kalvi pull request #101
Opened 2024-03-22 09:06 UTC by sidarth-23

## Summary
Refactored the cookieDestroyer function to send a POST request to the LOGOUT_URL with the refresh token and authorization header.  Upon successful logout, the function now deletes the "Authorization" and "Refresh" cookies and redirects to "/home".

- [x] Tested (Must)
- [ ] Test Case added
- [x] Build Successful (Must)
- [x] Sufficient Code comments added (Must)
- [ ] Attached Screenshots / Videos 
- [x] All Relevant Documents added

## Depends on

2024-03-22 09:50 UTC, yogai53 requested changes

2024-03-22 09:50 UTC, yogai53 commented on apps/admin/actions/cookie-destroy.ts
> +    console.error(e);
Should we need to send some error?

2024-03-22 09:50 UTC, yogai53 commented on apps/admin/actions/cookie-destroy.ts
> +    redirect("/home");
Why home? Shoudn't it be back to login page?

2024-03-22 10:03 UTC, sidarth-23 commented on apps/admin/actions/cookie-destroy.ts
> +    console.error(e);
I'm thinking we need to prevent user logout if the api fails to make sure the refresh token is dealt with

2024-03-22 10:04 UTC, sidarth-23 commented on apps/admin/actions/cookie-destroy.ts
> +    redirect("/home");
Yep. That was meant to be the route after middleware setup. Also fixed it in cookie setter

2024-03-22 10:06 UTC, sidarth-23 commented on apps/admin/actions/cookie-destroy.ts
> +    redirect("/home");
For the time being we are leaving logged out users in the starting page. But I think we will take care of the minor details sometime later

2024-03-22 11:54 UTC, yogai53 commented on apps/admin/actions/cookie-destroy.ts
> +    console.error(e);
Yes. But we should show some alert?

2024-03-22 11:54 UTC, yogai53 approved these changes

2024-03-26 09:09 UTC, elizabeththomas92 approved these changes

2024-03-26 09:30 UTC, merged