✨ feat[frontend]: middleware for user verification
kalvilabs/kalvi pull request #106
Opened 2024-03-28 07:49 UTC by sidarth-23

## Summary
- Added jwt verification in middleware to authorize only authenticated users into protected routes
- Altetered the route structure to simplify setting up middleware and making it maintainable.
- Fixed the link paths in app to support the new route structure ✨ Update cookieDestroyer to revalidatePath and redirect
- Update cookieDestroyer function to revalidatePath and redirect to maintain user session better.

### Video
https://www.loom.com/share/776a0e4d2b2f41f3b5801618dcc97572?sid=6636e8f3-5eb5-4dc1-8ddd-5ea4bd2b0fcf

- [x] Tested (Must)
- [ ] Test Case added
- [x] Build Successful (Must)
- [x] Sufficient Code comments added (Must)
- [x] Attached Screenshots / Videos 
- [x] All Relevant Documents added

## Depends on

2024-03-28 10:17 UTC, yaju09 requested changes

2024-03-28 10:17 UTC, yaju09 commented on apps/admin/middleware.ts
> +export const config = {
```suggestion
export const config = {
```
should this be placed in next js config  or this is the right place for the same?

2024-04-08 14:23 UTC, elizabeththomas92 approved these changes

2024-04-09 09:34 UTC, yogai53 approved these changes

2024-04-09 11:44 UTC, merged