feat: setup ui package structure starting with auth layout
kalvilabs/kalvi pull request #21
Opened 2024-02-15 12:07 UTC by sidarth-23

# Setting of the UI package for the entire codebase

## Summary
This commit is start off with the setting the code structure for the ui package that is going to be used across all the applications.

### The structure is
1. **src/components**
   * Where the react components required for the applications reside

2. **src/ lib**
   * Any helper function with regards to the ui. Ex: class merge

3. **src/partials**
   * Where an overall structure of components used resides. This is not to be exported to be directly used by applications, but be built on in the `src/components`
 
 
 ### Method to build reusable components
 - This is based on react composition - read this article for more details on it 
 https://felixgerschau.com/react-component-composition/
 
 ### Example code
 ```
 <AuthPage.PageWrapper pageTitle="Login" cardTitle="Login">
      <AuthPage.InputsWrapper>
            <AuthPage.InputField fieldName="Username" type="" />
            <AuthPage.InputField fieldName="Password" type="password" />
      </AuthPage.InputsWrapper>
      <AuthPage.FooterWrapper>
            <AuthPage.ButtonElement contentIn="Login" />
            <AuthPage.FooterContent>Enter a random text to see layout</AuthPage.FooterContent> 
     </AuthPage.FooterWrapper>
</AuthPage.PageWrapper>
 ```

## Checklist
- [ ] Tested (Must)
- [ ] Test Case added
- [ ] Build Successful (Must)
- [ ] Sufficient Code comments added (Must)
- [ ] Attached Screenshots / Videos 
- [ ] All Relevant Documents added

## Depends on

No dependencies for the PR

2024-02-15 12:18 UTC, yogai53 requested changes

2024-02-15 12:18 UTC, yogai53 commented on packages/ui/src/partials/card.tsx
> +import { cn } from "../lib/tw-class-merge"
Instead of using relative paths. use absolute path. Like @/lib/tw-class-merge

2024-02-15 12:18 UTC, yogai53 commented on packages/ui/src/components/auth-page/auth-page.tsx
> +} from "../../partials/card";
Use absolute path.

2024-02-15 12:18 UTC, yogai53 commented on packages/ui/src/components/auth-page/auth-page.tsx
> +          {cardTitle && <CardTitle>{cardTitle}</CardTitle>}
I don't think, we need this condition, since the props `cardTitle` seems to be mandatory in the function signature. .

2024-02-15 12:19 UTC, yogai53 commented
@sidarth-23 Please check the Checklist in the PR summary.

2024-02-15 12:39 UTC, sidarth-23 commented on packages/ui/src/components/auth-page/auth-page.tsx
> +          {cardTitle && <CardTitle>{cardTitle}</CardTitle>}
Removed the condition

2024-02-15 12:41 UTC, sidarth-23 commented
Added absolute pathing, but check if the configuration to each app is worth the effort. 

This is reference for why that is the case
https://github.com/vercel/turbo/discussions/620

2024-02-16 14:12 UTC, elizabeththomas92 approved these changes

2024-02-16 17:33 UTC, yaju09 approved these changes

2024-02-18 07:13 UTC, merged