feat: update login page UI components and remove unnecessary code in home page
kalvilabs/kalvi pull request #31
Opened 2024-02-19 09:51 UTC by sidarth-23

The login page UI components have been updated to match the latest design. The changes include:
- Added AuthPage component from "@repo/ui/components"
- Updated the layout and styling of the login form
- Removed unnecessary imports and code in the Home page component

## Summary

- [x] Tested (Must)
- [ ] Test Case added
- [x] Build Successful (Must)
- [x] Sufficient Code comments added (Must)
- [ ] Attached Screenshots / Videos 
- [x] All Relevant Documents added

## Depends on

2024-02-19 10:39 UTC, yogai53 approved these changes

2024-02-19 10:39 UTC, yogai53 commented on apps/admin/app/layout.tsx
> +      <body className="h-screen w-full">
import {Body} from "@repo/ui/xyz"
```suggestion
      <Body className="h-screen w-full">
```

2024-02-19 10:39 UTC, yogai53 commented on apps/admin/app/login/page.tsx
> +          placeholder="Password" />
Pls format it.

2024-02-19 10:44 UTC, yaju09 requested changes

2024-02-19 10:44 UTC, yaju09 commented on apps/admin/app/login/page.tsx
> +      cardDescription="Enter you details to get it"
```suggestion
      cardDescription="Enter your details to get it"
```

2024-02-20 06:10 UTC, elizabeththomas92 approved these changes

2024-02-20 06:14 UTC, sidarth-23 commented
Closing this as we changed the course of action of development

2024-02-20 06:14 UTC, closed without merging