feat: add registration page component
kalvilabs/kalvi pull request #32
Opened 2024-02-19 09:53 UTC by sidarth-23

Adds a new component for the registration page in the UI. The component includes input fields for first name, last name, email, and password. It also includes a button for submitting the registration form.

## Summary

- [ ] Tested (Must)
- [ ] Test Case added
- [ ] Build Successful (Must)
- [ ] Sufficient Code comments added (Must)
- [ ] Attached Screenshots / Videos 
- [ ] All Relevant Documents added

## Depends on

2024-02-19 10:41 UTC, yogai53 approved these changes

2024-02-19 10:41 UTC, yogai53 commented on apps/admin/app/register/page.tsx
> +        <AuthPage.ButtonElement contentIn="Login"/>
```suggestion
        <AuthPage.ButtonElement buttonTxt="Login"/>
```

2024-02-19 10:45 UTC, yaju09 requested changes

2024-02-19 10:45 UTC, yaju09 commented on apps/admin/app/register/page.tsx
> +      cardDescription="Enter you details to experience it"
```suggestion
      cardDescription="Enter your details to experience it"
```

2024-02-20 06:10 UTC, elizabeththomas92 approved these changes

2024-02-20 06:15 UTC, sidarth-23 commented
Closing this as we changed the course of action of development

2024-02-20 06:15 UTC, closed without merging