feat: add Forgot Password page component
kalvilabs/kalvi pull request #33
Opened 2024-02-19 09:54 UTC by sidarth-23

This commit adds a new component called LoginPage, which is responsible for rendering the Forgot Password page. The component includes a page wrapper, a card with a title and description, an input field for the email, and a button for requesting a password change.

## Summary

- [ ] Tested (Must)
- [ ] Test Case added
- [ ] Build Successful (Must)
- [ ] Sufficient Code comments added (Must)
- [ ] Attached Screenshots / Videos 
- [ ] All Relevant Documents added

## Depends on

2024-02-19 10:42 UTC, yogai53 approved these changes

2024-02-19 10:42 UTC, yogai53 commented on apps/admin/app/forgot-password/page.tsx
> +        <AuthPage.ButtonElement contentIn="Request Change"/>
```suggestion
        <AuthPage.ButtonElement btnTxt="Request Change"/>
```

2024-02-19 10:46 UTC, yaju09 requested changes

2024-02-19 10:46 UTC, yaju09 commented on apps/admin/app/forgot-password/page.tsx
> +      cardDescription="Enter you details to get it"
```suggestion
      cardDescription="Enter your details to get it"
```

2024-02-20 06:10 UTC, elizabeththomas92 approved these changes

2024-02-20 06:15 UTC, sidarth-23 commented
Closing this as we changed the course of action of development

2024-02-20 06:15 UTC, closed without merging