feat: add Checkbox component to auth page form and designed the auth layout
kalvilabs/kalvi pull request #34
Opened 2024-02-19 09:57 UTC by sidarth-23

The Checkbox component has been added to the auth page form to align with the design of the page. It allows users to select options with a checkbox.

## Summary

- [ ] Tested (Must)
- [ ] Test Case added
- [ ] Build Successful (Must)
- [ ] Sufficient Code comments added (Must)
- [ ] Attached Screenshots / Videos 
- [ ] All Relevant Documents added

## Depends on

2024-02-19 10:54 UTC, yogai53 requested changes
Please seggregate this into two PRs.

2024-02-19 10:54 UTC, yogai53 commented on packages/ui/src/partials/checkbox.tsx
> +"use client"
New PR please.

2024-02-19 10:54 UTC, yogai53 commented on packages/ui/package.json
> +    "@radix-ui/react-checkbox": "^1.0.4",
new PR

2024-02-19 10:54 UTC, yogai53 commented on packages/ui/src/components/auth-page/auth-page.tsx
> +function FormWrapper({
Can it be a new component

2024-02-19 10:54 UTC, yogai53 commented on packages/ui/src/components/auth-page/auth-page.tsx
> +function FormWrapper({
New file.

2024-02-19 10:54 UTC, yogai53 commented on packages/ui/src/components/auth-page/auth-page.tsx
> +function CheckboxField({
```suggestion
function RememberMeCheckboxField({
```

2024-02-19 10:54 UTC, yogai53 commented on packages/ui/src/components/auth-page/auth-page.tsx
> +        <svg
Create separate icon file.

2024-02-19 10:54 UTC, yogai53 commented on packages/ui/src/components/auth-page/auth-page.tsx
See if some of the components here can be moved to a new file or folder, if they are more generate and not auth specific.

2024-02-20 06:16 UTC, sidarth-23 commented
Closing this as we changed the course of action of development

2024-02-20 06:16 UTC, closed without merging