✨ feat: added layout for dashboard page
kalvilabs/kalvi pull request #90
Opened 2024-03-19 18:08 UTC by sidarth-23

## Summary
Added a new dashboard footer component to the project. This component includes functionality to control the sidebar visibility and display buttons for opening and closing the sidebar. The footer layout adjusts based on the sidebar state.

- Added DashboardSidebarFooter component
- Imported necessary icons and styles
- Implemented functionality to control sidebar visibility

- [ ] Tested (Must)
- [ ] Test Case added
- [ ] Build Successful (Must)
- [ ] Sufficient Code comments added (Must)
- [ ] Attached Screenshots / Videos 
- [ ] All Relevant Documents added

## Depends on

2024-03-20 07:58 UTC, sidarth-23 commented
We can merge the base branch before merging it into codebase to avoid the number of commits in the PR

2024-03-20 12:33 UTC, yogai53 approved these changes, later dismissed

2024-03-21 14:14 UTC, elizabeththomas92 requested changes

2024-03-21 14:14 UTC, elizabeththomas92 commented on packages/ui/src/components/dashboard-layout/content/body/card-title.tsx
is this file required ?

2024-03-21 14:51 UTC, elizabeththomas92 approved these changes

2024-03-22 08:41 UTC, yogai53 approved these changes

2024-03-22 08:46 UTC, merged