feat: Add GitHub and Google sign-in buttons
kalvilabs/kalvi pull request #95
Opened 2024-03-20 13:27 UTC by sidarth-23

## Summary
- Add GitHub sign-in button to allow users to sign in with GitHub.
- Add Google sign-in button to allow users to sign in with Google.
- These buttons will authenticate users and set cookies for access and refresh tokens.

- [x] Tested (Must)
- [ ] Test Case added
- [x] Build Successful (Must)
- [ ] Sufficient Code comments added (Must)
- [x] Attached Screenshots / Videos 
- [x] All Relevant Documents added

### Screenshot
![image](https://github.com/kalvilabs/kalvi/assets/58748190/82ec545e-d56b-434d-a909-e841683a62f1)

## Depends on
#88

2024-03-22 08:42 UTC, yogai53 submitted a review, later dismissed

2024-03-28 05:09 UTC, elizabeththomas92 requested changes

2024-03-28 05:09 UTC, elizabeththomas92 commented on apps/admin/components/google-signin.tsx
> +    (window as any)?.google?.accounts.id.initialize({
I see this being used at some places repeatedly ,maybe destructure and use directly? 

`const googleId = window?.google?.accounts?.id;`


```
googleId.initialize({
      client_id: clientId,
      callback: handleGoogleSignIn,
    });
```

2024-03-28 06:22 UTC, yaju09 requested changes

2024-03-28 06:22 UTC, yaju09 commented on apps/admin/components/github-signin.tsx
> +      console.error(err);
```suggestion
      console.error(err);
```
please remove console

2024-03-28 06:22 UTC, yaju09 commented on apps/admin/components/github-signin.tsx
> +  const [loginCallBackURL, setLoginCallBackURL] = useState(undefined);
```suggestion
  const [loginCallBackURL, setLoginCallBackURL] = useState();
```
is undefined is to be given explicitly?

2024-03-28 06:22 UTC, yaju09 commented on apps/admin/components/github-signin.tsx
> +    setLoginCallBackURL(`${origin}/` as any);
```suggestion
    setLoginCallBackURL(`${origin}/` as any);
``
is it possible to handle any?`

2024-03-28 06:22 UTC, yaju09 commented on apps/admin/components/google-signin.tsx
> +  const handleGoogleSignIn = async ({ clientId, credential }: any) => {
```suggestion
  const handleGoogleSignIn = async ({ clientId, credential }: any) => {
```
is it possible to address any?

2024-03-28 06:22 UTC, yaju09 commented on apps/admin/components/google-signin.tsx
> +      console.error(error);
```suggestion
      console.error(error);
```
is the above console required?

2024-03-28 06:22 UTC, yaju09 commented on apps/admin/components/google-signin.tsx
> +      console.log(err);
```suggestion
      console.log(err);
```
is the console required?

2024-03-28 06:43 UTC, sidarth-23 commented on apps/admin/components/google-signin.tsx
> +  const handleGoogleSignIn = async ({ clientId, credential }: any) => {
I think that is bit difficult for now

2024-03-28 08:45 UTC, elizabeththomas92 submitted a review, later dismissed

2024-03-28 09:51 UTC, yaju09 approved these changes

2024-04-08 14:22 UTC, elizabeththomas92 approved these changes

2024-04-09 09:33 UTC, yogai53 approved these changes

2024-04-09 09:38 UTC, merged